Feat/parser UI
Gidsss/UwUIDE pull request #117
Opened 2024-02-27 05:02 UTC by chaaals

## Description
PR implements Treeview UI for parser.

## Screenshot
Success:
![image](https://github.com/Gidsss/UwUIDE/assets/70326902/2a5d3ff1-5628-483f-8dfa-76e785c790fd)

With error logs:
![Screenshot 2024-02-27 130053](https://github.com/Gidsss/UwUIDE/assets/70326902/3f64dbdc-feb3-4fd1-a420-86cb455b40fa)

2024-02-27 10:23 UTC, Gidsss approved these changes

2024-03-04 07:51 UTC, Gidsss requested changes

2024-03-04 07:51 UTC, Gidsss commented on src/components/code_view.py
Add the ff code in CodeEditor class for QOL:
initial_text = "fwunc mainuwu-san() [[\n\n]]" # For QoL Purposes 
self.text.insert('1.0', initial_text)

2024-03-04 08:05 UTC, chaaals commented on src/components/code_view.py
cool idea

2024-03-04 08:16 UTC, Gidsss commented on src/components/code_view.py
Lagay na rin naten HAHAHA

2024-03-07 11:20 UTC, Gidsss approved these changes

2024-04-04 06:16 UTC, am-cid approved these changes

2024-04-04 06:16 UTC, merged