feat/additional-qol
Gidsss/UwUIDE pull request #319
Opened 2024-05-22 17:54 UTC by Gidsss

closes issue #314 and #313 

F3 - Auto Format
F4 - Quick Run

2024-05-22 18:24 UTC, chaaals requested changes
Sorry if madami, ideally with these changes, it will follow the same implementation we have on `Compile & Run`. Dapat nag i-iswitch lang yung mode ng `on_compile_and_run` to quick or compile modes

2024-05-22 18:24 UTC, chaaals commented on src/uwu.py
> +
may not be necessary, `on_compiler_run` can have an extra parameter to use quick mode para hindi `code_editor.start()` ang gamitin niya

2024-05-22 18:24 UTC, chaaals commented on src/components/code_view.py
> +            self.parent.master.update_analyzer_tabs_and_logs(active_editor, lx_res, p_res, a_res)
if implemented correctly, `on_compiler_run` should update the tabs and logs na, this won't be necessary

2024-05-22 18:24 UTC, chaaals commented on src/components/command_menu.py
> +            command=self.code_view.quick_run
e.g. `self.code_view.on_compile_and_run(compile=false)`

2024-05-22 18:24 UTC, chaaals commented on src/components/code_view.py
> +                    compiler.run_python()  # Run the Python transpiled code
this is correct, `quick_run` should be getting the transpiled program, verifying, and running it sa cmd.

evaluation should be done before this is called. try to limit na ang nangyayari lang sa quick run is this

2024-05-22 18:24 UTC, chaaals commented on src/components/code_view.py
> +    def quick_run(self):
consider moving this to `CodeEditor`, andon kasi lahat ng pag run ng program, at that level no need i-check updated source code

2024-05-25 07:17 UTC, Gidsss commented
![image](https://github.com/Gidsss/UwUIDE/assets/88811389/40f6faa9-6a6f-44bf-a698-bd5156b6f090)
Demo:
https://github.com/Gidsss/UwUIDE/assets/88811389/091cce8b-4ae6-4f76-9f06-0b033d39bc94

2024-05-25 07:29 UTC, am-cid approved these changes

2024-05-25 07:42 UTC, chaaals requested changes
Noticed that lines 421, 433, 438, and 440 in `src/components/code_view.py` had these changes, why?

2024-05-25 07:42 UTC, chaaals commented on src/components/code_view.py
> +        self.parent.master.code_panel.update_compiler_logs(editor=self.editor, is_compiling=False, is_formatting=True)
why this change?

2024-05-25 08:41 UTC, Gidsss commented on src/components/code_view.py
> +        self.parent.master.code_panel.update_compiler_logs(editor=self.editor, is_compiling=False, is_formatting=True)
my bad g hahahaha

2024-05-25 09:48 UTC, HolyShaq approved these changes

2024-05-25 10:58 UTC, chaaals approved these changes

2024-05-25 11:08 UTC, merged