Refactor/Reserved words and symbols
Gidsss/UwUIDE pull request #41
Opened 2023-11-09 12:49 UTC by chaaals

# Changelog
This PR contains changes on TokenType reserved words and symbols

2023-11-10 15:25 UTC, HolyShaq requested changes
![Screenshot_20231110_232500_GitHub.jpg](https://github.com/Gidsss/UwUIDE/assets/66175571/5a4040ff-a4a8-450d-85d4-00829d3e7839)

Papalitan token types for these as well to match the lexeme

Tas tanggalin si negative token type

2023-11-10 15:25 UTC, HolyShaq commented on src/lexer/token.py
>      OPEN_BRACE = ("OPEN_BRACE", "open_brace")  # {
```suggestion
    OPEN_BRACE = ({", "open_brace")  # {
```

2023-11-10 15:27 UTC, HolyShaq reviewed
![Screenshot_20231110_232656_GitHub.jpg](https://github.com/Gidsss/UwUIDE/assets/66175571/a99d0d6e-adae-476f-85e8-262cfa2ebd67)

Change this to "-" din pala

2023-11-10 16:16 UTC, Gidsss commented
Done bro

2023-11-10 17:39 UTC, am-cid commented
> ![Screenshot_20231110_232656_GitHub.jpg](https://user-images.githubusercontent.com/66175571/282101324-a99d0d6e-adae-476f-85e8-262cfa2ebd67.jpg)
> 
> Change this to "-" din pala

should probably just remove type indicator altogether and let syntax handle it whether it's a minus sign or a type indicator

2023-11-11 13:10 UTC, HolyShaq commented
> > ![Screenshot_20231110_232656_GitHub.jpg](https://user-images.githubusercontent.com/66175571/282101324-a99d0d6e-adae-476f-85e8-262cfa2ebd67.jpg)
> > Change this to "-" din pala
> 
> should probably just remove type indicator altogether and let syntax handle it whether it's a minus sign or a type indicator

Alright, that's smart. I'm honestly just reluctant to get rid of my code for that 😭😭 HAHAHAHAHAHHAA

2023-11-11 14:04 UTC, merged